# compose.yaml
services:
  frankenphp:
    build:
      context: .
    entrypoint: php artisan octane:frankenphp --max-requests=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/vendor
    networks:
      - app-network
    depends_on:
      - mysql
      - node
  mysql:
    image: mysql/mysql-server:${MYSQL_VERSION:-8.0}
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -p${DB_PASSWORD}
      retries: 3
      timeout: 5s
    networks:
      - app-network
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Docker Volumes
#volumes:
#  vendor:
#  node_modules:
