# Set the base image
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy `package.json` and `package-lock.json`
COPY package*.json ./

# Install project dependencies
RUN npm install --legacy-peer-deps

# Copy project files into the docker image
COPY --link . ./

# Expose the port Vite runs on
EXPOSE 5173

# Start the Vite server
CMD ["npm", "run", "dev"]
